### PR TITLE
WIP: Added buffer support to handle large outputs to stdout

### PR DESCRIPTION
**Pull request by garrytrinder**
Solves https://github.com/pnp/office365-cli/issues/1266

### CODE REVIEW

**Review by waldekmastykarz — CHANGES_REQUESTED** [review]
I think we might have some difference between how the output is rendered now and how it was previously. See the attached image. Not sure if there are any side-effects to it or not, but let's see if we could keep the output the same:

Screenshot 2020-01-15 at 10 14 37

First output is after the change, second before the change.

**Comment by garrytrinder** [comment]
Good spot, let me get back to you.

**Comment by garrytrinder** [comment]
Looks like this is output from the shell, assuming you use ‘zsh‘ which is the default shell on MacOS since Catalina, the highlighted ‘%‘ denotes a "partial line"

https://unix.stackexchange.com/questions/167582/why-zsh-ends-a-line-with-a-highlighted-percent-symbol#167600

**Comment by garrytrinder** [comment]
This isn’t working as I had hoped after more testing this evening. I’ll take a look again tomorrow, leave this with me.

**Pull request closed without merging**
